### ISSUE TITLE
No detection at higher camera resolution 

### ISSUE THREAD

**Issue by spirosperos** [NVIDIA-ISAAC-ROS/isaac_ros_apriltag#24]
I can successfully run detection with a Realsense set to resolution 640x480. However, when I increase the resolution to 1920x1080, I am not getting any detection, no matter how far or close the marker is from the camera. Why is this happening, and how could I adjust the parameters so that the detection is possible at a higher resolution? Possibly also at 4K? Thank you

**Comment by jaiveersinghNV** [comment]
We're not sure what the problem is yet, but we have a couple questions to help us narrow it down:
- Are you using the same RealSense camera between tests, or are you switching between different cameras with different resolutions?
- Could you please verify that you have set the `size` ROS parameter correctly, to correspond with the real-world size of the tag in meters?
- Could you also verify that the `sensor_msgs/CameraInfo` messages being produced by the RealSense correctly match the new 1920x1080 resolution?
