### ISSUE TITLE
ROS 1 node

### ISSUE THREAD

**Issue by gftabor** [NVIDIA-ISAAC-ROS/isaac_ros_apriltag#25]
I am very interested in switched to GPU accelerated tag detection. April tag tracking is part of the work flow for many projects in my lab but like many we are all still using ROS1.

Could you make a ROS1 node for this?

**Comment by gordongrigor** [comment]
It's understandable that projects on ROS1, can benefit from our GPU acceleration work in ROS 2.  We are not releasing packages for ROS 1 because Melodic goes end of life this year and Noetic goes end of life in 2025.  

With our upcoming release this month for GTC, you could lift the AprilTag library and header from the ROS 2 node, into http://wiki.ros.org/apriltag_ros.

**Comment by gftabor** [comment]
Thanks @gordongrigor 

https://nvidia-isaac-ros.github.io/concepts/fiducials/apriltag/tutorial_apriltag_ros1_bridge.html
